import os


class AppConfig:
    # S3 SOURCE
    S3_ORIGIN_CONN_ID = os.getenv('S3_ORIGIN_CONN_ID')
    S3_BUCKET_FINAL_PROJECT = os.getenv('S3_BUCKET_FINAL_PROJECT')
    S3_KEY_CURRENCIES_HISTORY = os.getenv('S3_KEY_CURRENCIES_HISTORY')
    S3_KEY_TRANSACTIONS_BATCH = os.getenv('S3_KEY_TRANSACTIONS_BATCH')

    # LOCAL DATA DIRECTORY
    FS_DATADIR_CONN_ID = os.getenv('FS_DATADIR_CONN_ID')
    FS_PATH_TRANSACTIONS_INC = os.getenv('FS_PATH_TRANSACTIONS_INC')
    FS_PATH_CURRENCIES_INC = os.getenv('FS_PATH_CURRENCIES_INC')

    # LOCAL SQL DIRECTORY
    FS_SQLDIR_CONN_ID=os.getenv('FS_SQLDIR_CONN_ID')

    # VERTICA DWH
    VERTICA_WAREHOUSE_CONN_ID = os.getenv('VERTICA_WAREHOUSE_CONN_ID')
    VERTICA_TABLE_TRANSACTIONS = os.getenv('VERTICA_TABLE_TRANSACTIONS')
    VERTICA_TABLE_CURRENCIES = os.getenv('VERTICA_TABLE_CURRENCIES')
    VERTICA_LOGIN = os.getenv('VERTICA_LOGIN')
    VERTICA_PASSWORD = os.getenv('VERTICA_PASSWORD')
